const SONGS = [
  // ─────────────────────────────────────────────────────────────────────────
  //  チュートリアル — 大きな古時計 (Grandfather's Clock / H.C. Work)
  //  ハ長調なので主要音がホームポジション(F J D K S L)に割り当たる。
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "tutorial_clock",
    title: "大きな古時計",
    composer: "H.C. Work  (チュートリアル)",
    level: 0,
    tutorial: true,
    bpm: 60,
    // ハ長調・メロディー譜どおり。小学生が弾く音域に合わせて
    // 真ん中のド(ド=C4)始まり・出だしのソ=G3。伴奏(accomp)は
    // tutorial では鳴らさない (game.js の maxLayer=0)。
    // キー割り当ては出現頻度順に自動決定されるので、ヒントでは
    // 文字キー名ではなく「光ったキーを表示の指で」と指の習慣を教える。
    events: [
      // ══ Verse 1 ══ 「おおきなのっぽのふるどけい おじいさんのとけい」
      {notes:["G3"], accomp:[],               hint:"光ったキーを、画面下に出る指で押そう"},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["B3"], accomp:["G1","B1","D2"], hint:"押したら指はホームポジションに戻すのがコツ"},
      {notes:["C4"], accomp:[]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["D4"], accomp:[]},
      {notes:["E4"], accomp:["C2","E2","G2"], hint:"あせらなくてOK。タイルがラインに来たら押そう"},
      {notes:["E4"], accomp:[]},
      {notes:["F4"], accomp:["F1","A1","C2"]},
      {notes:["E4"], accomp:[]},
      {notes:["A4"], accomp:["F1","A1","C2"], hint:"高い音もホームポジションから指をのばして"},
      {notes:["D4"], accomp:["G1","B1","D2"]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["C4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["B3"], accomp:["G1","B1","D2"]},
      {notes:["A3"], accomp:[]},
      {notes:["B3"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"], hint:"1番のメロディーが弾けたね！"},

      // ══ Verse 2 ══ (くりかえし)
      {notes:["G3"], accomp:[],               hint:"もう一度くりかえし。リズムに乗ろう"},
      {notes:["G3"], accomp:["C2","E2","G2"]},
      {notes:["C4"], accomp:[]},
      {notes:["B3"], accomp:["G1","B1","D2"]},
      {notes:["C4"], accomp:[]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["D4"], accomp:[]},
      {notes:["E4"], accomp:["C2","E2","G2"]},
      {notes:["E4"], accomp:[]},
      {notes:["F4"], accomp:["F1","A1","C2"]},
      {notes:["E4"], accomp:[]},
      {notes:["A4"], accomp:["F1","A1","C2"]},
      {notes:["D4"], accomp:["G1","B1","D2"]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["C4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["B3"], accomp:["G1","B1","D2"]},
      {notes:["A3"], accomp:[]},
      {notes:["B3"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},

      // ══ Bridge ══ 「ひゃくねん いつもうごいていた」
      {notes:["C4"], accomp:["C2","E2","G2"], hint:"ここからメロディーが変わるよ"},
      {notes:["E4"], accomp:[]},
      {notes:["G4"], accomp:["C2","E2","G2"]},
      {notes:["E4"], accomp:[]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["B3"], accomp:["G1","B1","D2"]},
      {notes:["C4"], accomp:[]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["B3"], accomp:[]},
      {notes:["A3"], accomp:["F1","A1","C2"]},
      {notes:["G3"], accomp:["G1","B1","D2"]},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["E4"], accomp:[]},
      {notes:["G4"], accomp:["C2","E2","G2"]},
      {notes:["E4"], accomp:[]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["B3"], accomp:["G1","B1","D2"]},
      {notes:["C4"], accomp:[]},
      {notes:["D4"], accomp:[]},

      // ══ Bridge tail ══ 「いまは もう うごかない」へ
      {notes:["G3"], accomp:[],               hint:"だんだん盛り上がってきた！"},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["C4"], accomp:[]},
      {notes:["D4"], accomp:["G1","B1","D2"]},
      {notes:["E4"], accomp:["C2","E2","G2"]},
      {notes:["E4"], accomp:[]},
      {notes:["F4"], accomp:["F1","A1","C2"]},
      {notes:["E4"], accomp:[]},
      {notes:["A4"], accomp:["F1","A1","C2"]},
      {notes:["D4"], accomp:["G1","B1","D2"]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["C4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["B3"], accomp:["G1","B1","D2"]},
      {notes:["A3"], accomp:[]},
      {notes:["B3"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},

      // ══ Chorus (サビ) ══ 「いまは もう うごかない そのとけい」
      {notes:["G3"], accomp:["C2","E2","G2"], hint:"サビ！いちばん有名なところ"},
      {notes:["G3"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["G3"], accomp:[]},
      {notes:["G3"], accomp:[]},
      {notes:["A3"], accomp:["F1","A1","C2"]},
      {notes:["G3"], accomp:[]},
      {notes:["G3"], accomp:[]},
      {notes:["E4"], accomp:["C2","E2","G2"]},
      {notes:["G3"], accomp:[]},
      {notes:["E4"], accomp:[]},
      {notes:["G3"], accomp:["C2","E2","G2"]},
      {notes:["G3"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["G3"], accomp:[]},
      {notes:["G3"], accomp:[]},
      {notes:["A3"], accomp:["F1","A1","C2"]},
      {notes:["G3"], accomp:[]},
      {notes:["G3"], accomp:[]},
      {notes:["E4"], accomp:["C2","E2","G2"]},
      {notes:["G3"], accomp:[]},

      // ══ Final Verse ══ 「もう うごかない そのとけい」
      {notes:["E4"], accomp:[],               hint:"最後のメロディー！フィナーレ"},
      {notes:["G3"], accomp:[]},
      {notes:["G3"], accomp:["C2","E2","G2"]},
      {notes:["C4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["D4"], accomp:["G1","B1","D2"]},
      {notes:["E4"], accomp:["C2","E2","G2"]},
      {notes:["E4"], accomp:[]},
      {notes:["F4"], accomp:["F1","A1","C2"]},
      {notes:["E4"], accomp:[]},
      {notes:["A4"], accomp:["F1","A1","C2"]},
      {notes:["D4"], accomp:["G1","B1","D2"]},
      {notes:["D4"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["C4"], accomp:[]},
      {notes:["C4"], accomp:[]},
      {notes:["B3"], accomp:["G1","B1","D2"], hint:"あと少し！"},
      {notes:["A3"], accomp:[]},
      {notes:["B3"], accomp:[]},
      {notes:["C4"], accomp:["C2","E2","G2"]},
      {notes:["C4"], accomp:["C2","E2","G2"], hint:"おめでとう！大きな古時計をクリア！"},
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  Für Elise — L.v. Beethoven   (初級: A-B-A-C-A 完全版)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "fur_elise",
    title: "エリーゼのために",
    composer: "L.v. ベートーヴェン",
    level: 1,
    bpm: 72,
    events: [
      // ===== A Section 1 =====
      // phrase 1a
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      // phrase 1b (same motif, different ending)
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},

      // ===== B Section =====
      // First episode — C / G / F major. Single-note melody (as in the
      // original); clean diatonic accompaniment so nothing clashes.
      {notes:["B4"],  accomp:["G2","D3","G3"]},   // G7 → leading into C
      {notes:["C5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","B2","D3"]},   // G
      {notes:["E5"],  accomp:["C3","G3","C4"]},   // C
      {notes:["G4"],  accomp:["C3","E3","G3"]},   // C
      {notes:["F5"],  accomp:["F2","C3","F3","A3"]}, // F
      {notes:["E5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","B2","D3"]},   // G
      {notes:["F4"],  accomp:["F2","A2","C3"]},   // F
      {notes:["E5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","D3"]},        // G
      {notes:["C5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["E4"],  accomp:["E2","G#2","B2","E3"]}, // E7 (turn to A minor)
      {notes:["D5"],  accomp:["E2","B2"]},        // E
      {notes:["C5"],  accomp:["A2","E3","A3"]},   // Am
      {notes:["B4"],  accomp:["E2","G#2","B2"]},  // E7
      // return to A
      {notes:["E5"],  accomp:["A2"]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["E2","G#2"]},

      // ===== A Section 2 =====
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},

      // ===== C Section — stormy passage in A minor =====
      // Left hand: continuous arpeggios. Right hand: melody + lower octave on downbeats.
      {notes:["A4","A3"], accomp:["A2","E3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["C4"],      accomp:["A2","C3","E3","A3"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["F4","F3"], accomp:["F2","C3","F3"]},
      {notes:["C4"],      accomp:["F2","A2","C3"]},
      {notes:["A3"],      accomp:["F2","A2"]},
      {notes:["E4"],      accomp:["E2","G#2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2","E3"]},
      {notes:["G#3"],     accomp:["E2","G#2","B2"]},
      // E7 tension
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      {notes:["E4"],      accomp:["E2","G#2","B2"]},
      {notes:["D#4"],     accomp:["E2","G#2"]},
      {notes:["E4"],      accomp:["E2","B2","E3"]},
      {notes:["D#4"],     accomp:["E2","G#2"]},
      {notes:["E4"],      accomp:["E2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2","E3"]},
      {notes:["D4"],      accomp:["E2","G#2"]},
      {notes:["C4"],      accomp:["A2","E3","A3"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      // ascending run back to A
      {notes:["A3"],      accomp:["A2","E3"]},
      {notes:["B3"],      accomp:["E2","G#2","B2"]},
      {notes:["C4"],      accomp:["A2","C3","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["F4"],      accomp:["F2","C3","A3"]},
      {notes:["E4"],      accomp:["A2","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["C4"],      accomp:["E2","G#2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},

      // ===== A Section 3 — Final =====
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3","E3","A3"]},  // final chord
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  Rondo alla Turca — W.A. Mozart   (上級: 慣れてきたら)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "turkish_march",
    title: "トルコ行進曲",
    composer: "W.A. モーツァルト",
    level: 2,
    bpm: 60,
    events: [
      // ===== A Section — Rondo theme (A minor) =====
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["D5"],  accomp:["A2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["E5"],  accomp:["E3","A3"]},
      {notes:["F5"],  accomp:["A2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:["E2","G#2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["E2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["G#2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:["E3"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:[]},
      {notes:["F#4"], accomp:["D3"]},
      {notes:["E4"],  accomp:["E2","G#2","B2"]},

      // ===== Episode — running scales =====
      {notes:["E5"],  accomp:["C3","E3","G3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["A5"],  accomp:["C3","G3"]},
      {notes:["G5"],  accomp:["G2"]},
      {notes:["F5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["E5"],  accomp:["C3","E3","G3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["A5"],  accomp:["C3","G3"]},
      {notes:["G5"],  accomp:["G2","B2","D3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:["C3","E3","G3"]},
      {notes:["D5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["F5"],  accomp:["C3","G3"]},
      {notes:["E5"],  accomp:["G2","B2"]},
      {notes:["D5"],  accomp:[]},

      // ===== A Section return + cadence =====
      {notes:["C5"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["E2","G#2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["C5"],  accomp:["A2"]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["F5"],  accomp:["A2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:["E2","G#2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["B4"],  accomp:["E3","A3"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["E2","G#2","B2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["E5"],  accomp:["A2"]},
      {notes:["F5"],  accomp:[]},
      {notes:["D5"],  accomp:["E2","B2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4","C5","E5"], accomp:["A2","E3","A3"]},
    ],
  },
];
