const SONGS = [
  // ─────────────────────────────────────────────────────────────────────────
  //  Für Elise — L.v. Beethoven   (初級: A-B-A-C-A 完全版)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "fur_elise",
    title: "エリーゼのために",
    composer: "L.v. ベートーヴェン",
    level: 1,
    bpm: 72,
    events: [
      // ===== A Section 1 =====
      // phrase 1a
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      // phrase 1b (same motif, different ending)
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},

      // ===== B Section =====
      // First episode — C / G / F major. Single-note melody (as in the
      // original); clean diatonic accompaniment so nothing clashes.
      {notes:["B4"],  accomp:["G2","D3","G3"]},   // G7 → leading into C
      {notes:["C5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","B2","D3"]},   // G
      {notes:["E5"],  accomp:["C3","G3","C4"]},   // C
      {notes:["G4"],  accomp:["C3","E3","G3"]},   // C
      {notes:["F5"],  accomp:["F2","C3","F3","A3"]}, // F
      {notes:["E5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","B2","D3"]},   // G
      {notes:["F4"],  accomp:["F2","A2","C3"]},   // F
      {notes:["E5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","D3"]},        // G
      {notes:["C5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["E4"],  accomp:["E2","G#2","B2","E3"]}, // E7 (turn to A minor)
      {notes:["D5"],  accomp:["E2","B2"]},        // E
      {notes:["C5"],  accomp:["A2","E3","A3"]},   // Am
      {notes:["B4"],  accomp:["E2","G#2","B2"]},  // E7
      // return to A
      {notes:["E5"],  accomp:["A2"]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["E2","G#2"]},

      // ===== A Section 2 =====
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},

      // ===== C Section — stormy passage in A minor =====
      // Left hand: continuous arpeggios. Right hand: melody + lower octave on downbeats.
      {notes:["A4","A3"], accomp:["A2","E3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["C4"],      accomp:["A2","C3","E3","A3"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["F4","F3"], accomp:["F2","C3","F3"]},
      {notes:["C4"],      accomp:["F2","A2","C3"]},
      {notes:["A3"],      accomp:["F2","A2"]},
      {notes:["E4"],      accomp:["E2","G#2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2","E3"]},
      {notes:["G#3"],     accomp:["E2","G#2","B2"]},
      // E7 tension
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      {notes:["E4"],      accomp:["E2","G#2","B2"]},
      {notes:["D#4"],     accomp:["E2","G#2"]},
      {notes:["E4"],      accomp:["E2","B2","E3"]},
      {notes:["D#4"],     accomp:["E2","G#2"]},
      {notes:["E4"],      accomp:["E2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2","E3"]},
      {notes:["D4"],      accomp:["E2","G#2"]},
      {notes:["C4"],      accomp:["A2","E3","A3"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      // ascending run back to A
      {notes:["A3"],      accomp:["A2","E3"]},
      {notes:["B3"],      accomp:["E2","G#2","B2"]},
      {notes:["C4"],      accomp:["A2","C3","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["F4"],      accomp:["F2","C3","A3"]},
      {notes:["E4"],      accomp:["A2","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["C4"],      accomp:["E2","G#2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},

      // ===== A Section 3 — Final =====
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3","E3","A3"]},  // final chord
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  Rondo alla Turca — W.A. Mozart   (上級: 慣れてきたら)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "turkish_march",
    title: "トルコ行進曲",
    composer: "W.A. モーツァルト",
    level: 2,
    bpm: 60,
    events: [
      // ===== A Section — Rondo theme (A minor) =====
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["D5"],  accomp:["A2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["E5"],  accomp:["E3","A3"]},
      {notes:["F5"],  accomp:["A2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:["E2","G#2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["E2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["G#2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:["E3"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:[]},
      {notes:["F#4"], accomp:["D3"]},
      {notes:["E4"],  accomp:["E2","G#2","B2"]},

      // ===== Episode — running scales =====
      {notes:["E5"],  accomp:["C3","E3","G3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["A5"],  accomp:["C3","G3"]},
      {notes:["G5"],  accomp:["G2"]},
      {notes:["F5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["E5"],  accomp:["C3","E3","G3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["A5"],  accomp:["C3","G3"]},
      {notes:["G5"],  accomp:["G2","B2","D3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:["C3","E3","G3"]},
      {notes:["D5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["F5"],  accomp:["C3","G3"]},
      {notes:["E5"],  accomp:["G2","B2"]},
      {notes:["D5"],  accomp:[]},

      // ===== A Section return + cadence =====
      {notes:["C5"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["E2","G#2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["C5"],  accomp:["A2"]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["F5"],  accomp:["A2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:["E2","G#2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["B4"],  accomp:["E3","A3"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["E2","G#2","B2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["E5"],  accomp:["A2"]},
      {notes:["F5"],  accomp:[]},
      {notes:["D5"],  accomp:["E2","B2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4","C5","E5"], accomp:["A2","E3","A3"]},
    ],
  },
];
