const SONGS = [
  // ─────────────────────────────────────────────────────────────────────────
  //  チュートリアル — 大きな古時計 (Grandfather's Clock / H.C. Work)
  //  ハ長調なので主要音がホームポジション(F J D K S L)に割り当たる。
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "tutorial_clock",
    title: "大きな古時計",
    composer: "H.C. Work  (チュートリアル)",
    level: 0,
    tutorial: true,
    bpm: 58,
    // Key assignments (determined by frequency):
    //   G4→F(左人差) C4→J(右人差) E4→D(左中) D4→K(右中)
    //   B3→S(左薬)   A4→L(右薬)   A3→A(左小) F4→G
    events: [
      // ══ Verse A ══════════════════════════════════════════════════════
      // 「おおきな のっぽの」
      {notes:["G4"], accomp:["C3","E3","G3"], hint:"Fキー！左手の人差し指でスタート"},
      {notes:["C4"], accomp:["C3","E3","G3"], hint:"Jキー！右手の人差し指"},
      {notes:["B3"], accomp:[],               hint:"Sキー — 左手の薬指"},
      {notes:["C4"], accomp:[],               hint:"Jにもどろう"},
      {notes:["D4"], accomp:["G2","B2","D3"], hint:"Kキー — 右手の中指"},
      {notes:["C4"], accomp:[],               hint:"Jにもどろう"},
      {notes:["D4"], accomp:[],               hint:"Kキー、もう一度"},
      // 「ふるどけい」
      {notes:["E4"], accomp:["C3","E3","G3"], hint:"Dキー — 左手の中指"},
      {notes:["E4"], accomp:[],               hint:"もう一度Dキー！"},
      {notes:["F4"], accomp:["F2","A2","C3"], hint:"Gキー — 人差し指を少し右へ"},
      {notes:["E4"], accomp:[],               hint:"Dにもどろう"},
      {notes:["A4"], accomp:["F2","A2","C3"], hint:"Lキー — 右手の薬指！"},
      // 「おじいさんの とけい」
      {notes:["D4"], accomp:["G2","B2","D3"], hint:"Kキーにもどろう"},
      {notes:["D4"], accomp:[],               hint:"もう一度K！"},
      {notes:["C4"], accomp:["C3","E3","G3"], hint:"Jにもどろう"},
      {notes:["C4"], accomp:[]},
      {notes:["C4"], accomp:[],               hint:"いい調子！"},
      {notes:["B3"], accomp:[],               hint:"Sキー — 左薬指"},
      // 「おじいさんの たんじょうびに」
      {notes:["A3"], accomp:[],               hint:"Aキー！左手の小指"},
      {notes:["B3"], accomp:[],               hint:"Sにもどろう"},
      {notes:["C4"], accomp:["C3","E3","G3"], hint:"前半ゴール！"},

      // ══ Chorus ═══════════════════════════════════════════════════════
      // 「おおきな のっぽのふるどけい」
      {notes:["G4"], accomp:["C3","E3","G3"], hint:"サビ！Fキーが続くよ"},
      {notes:["G4"], accomp:[],               hint:"Fキー！"},
      {notes:["C4"], accomp:["C3","G3"],      hint:"Jへ！"},
      {notes:["G4"], accomp:[],               hint:"Fにもどろう"},
      {notes:["G4"], accomp:[]},
      {notes:["A4"], accomp:["F2","A2","C3"], hint:"Lキー！"},
      {notes:["G4"], accomp:[],               hint:"Fにもどろう"},
      {notes:["G4"], accomp:[]},
      {notes:["E4"], accomp:["C3","E3","G3"], hint:"Dキー！"},
      {notes:["G4"], accomp:[],               hint:"Fにもどろう"},
      {notes:["E4"], accomp:[]},
      // 「おじいさんといっしょに」
      {notes:["G4"], accomp:["C3","E3","G3"], hint:"リズムに乗ってきた！"},
      {notes:["G4"], accomp:[]},
      {notes:["C4"], accomp:["C3","G3"],      hint:"Jキー！"},
      {notes:["G4"], accomp:[],               hint:"Fにもどろう"},
      {notes:["G4"], accomp:[]},
      {notes:["A4"], accomp:["F2","A2","C3"], hint:"Lキー！"},
      {notes:["G4"], accomp:[],               hint:"Fにもどろう"},
      {notes:["G4"], accomp:[]},
      {notes:["E4"], accomp:["C3","E3","G3"], hint:"Dキー！"},
      {notes:["G4"], accomp:["C3","E3","G3"], hint:"Fでサビ終了！"},

      // ══ Final Verse ══════════════════════════════════════════════════
      // 「いまもうごいている」
      {notes:["E4"], accomp:[],               hint:"最後のセクション！D"},
      {notes:["G4"], accomp:[],               hint:"F"},
      {notes:["G4"], accomp:[],               hint:"F"},
      {notes:["C4"], accomp:["C3","E3","G3"], hint:"J"},
      {notes:["C4"], accomp:[],               hint:"J"},
      {notes:["D4"], accomp:["G2","B2","D3"], hint:"Kキー！"},
      // 「おじいさんの とけい」
      {notes:["E4"], accomp:["C3","E3","G3"], hint:"D"},
      {notes:["E4"], accomp:[]},
      {notes:["F4"], accomp:["F2","A2","C3"], hint:"Gキー"},
      {notes:["E4"], accomp:[],               hint:"D"},
      {notes:["A4"], accomp:["F2","A2","C3"], hint:"Lキー！"},
      {notes:["D4"], accomp:["G2","B2","D3"], hint:"K"},
      {notes:["D4"], accomp:[],               hint:"K"},
      {notes:["C4"], accomp:["C3","E3","G3"], hint:"J"},
      {notes:["C4"], accomp:[]},
      {notes:["C4"], accomp:[],               hint:"あと少し！"},
      {notes:["B3"], accomp:[],               hint:"S"},
      {notes:["A3"], accomp:[],               hint:"Aキー！小指"},
      {notes:["B3"], accomp:[],               hint:"S"},
      {notes:["C4"], accomp:["C3","E3","G3"]},
      // Final note
      {notes:["C4"], accomp:["C3","E3","G3"], hint:"おめでとう！大きな古時計をクリア！"},
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  Für Elise — L.v. Beethoven   (初級: A-B-A-C-A 完全版)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "fur_elise",
    title: "エリーゼのために",
    composer: "L.v. ベートーヴェン",
    level: 1,
    bpm: 72,
    events: [
      // ===== A Section 1 =====
      // phrase 1a
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      // phrase 1b (same motif, different ending)
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},

      // ===== B Section =====
      // First episode — C / G / F major. Single-note melody (as in the
      // original); clean diatonic accompaniment so nothing clashes.
      {notes:["B4"],  accomp:["G2","D3","G3"]},   // G7 → leading into C
      {notes:["C5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","B2","D3"]},   // G
      {notes:["E5"],  accomp:["C3","G3","C4"]},   // C
      {notes:["G4"],  accomp:["C3","E3","G3"]},   // C
      {notes:["F5"],  accomp:["F2","C3","F3","A3"]}, // F
      {notes:["E5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","B2","D3"]},   // G
      {notes:["F4"],  accomp:["F2","A2","C3"]},   // F
      {notes:["E5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["D5"],  accomp:["G2","D3"]},        // G
      {notes:["C5"],  accomp:["C3","E3","G3"]},   // C
      {notes:["E4"],  accomp:["E2","G#2","B2","E3"]}, // E7 (turn to A minor)
      {notes:["D5"],  accomp:["E2","B2"]},        // E
      {notes:["C5"],  accomp:["A2","E3","A3"]},   // Am
      {notes:["B4"],  accomp:["E2","G#2","B2"]},  // E7
      // return to A
      {notes:["E5"],  accomp:["A2"]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["E2","G#2"]},

      // ===== A Section 2 =====
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},

      // ===== C Section — stormy passage in A minor =====
      // Left hand: continuous arpeggios. Right hand: melody + lower octave on downbeats.
      {notes:["A4","A3"], accomp:["A2","E3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["C4"],      accomp:["A2","C3","E3","A3"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["F4","F3"], accomp:["F2","C3","F3"]},
      {notes:["C4"],      accomp:["F2","A2","C3"]},
      {notes:["A3"],      accomp:["F2","A2"]},
      {notes:["E4"],      accomp:["E2","G#2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2","E3"]},
      {notes:["G#3"],     accomp:["E2","G#2","B2"]},
      // E7 tension
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      {notes:["E4"],      accomp:["E2","G#2","B2"]},
      {notes:["D#4"],     accomp:["E2","G#2"]},
      {notes:["E4"],      accomp:["E2","B2","E3"]},
      {notes:["D#4"],     accomp:["E2","G#2"]},
      {notes:["E4"],      accomp:["E2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2","E3"]},
      {notes:["D4"],      accomp:["E2","G#2"]},
      {notes:["C4"],      accomp:["A2","E3","A3"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},
      // ascending run back to A
      {notes:["A3"],      accomp:["A2","E3"]},
      {notes:["B3"],      accomp:["E2","G#2","B2"]},
      {notes:["C4"],      accomp:["A2","C3","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["E4"],      accomp:["A2","C3","E3"]},
      {notes:["F4"],      accomp:["F2","C3","A3"]},
      {notes:["E4"],      accomp:["A2","E3"]},
      {notes:["D4"],      accomp:["A2","C3"]},
      {notes:["C4"],      accomp:["E2","G#2","B2"]},
      {notes:["B3"],      accomp:["E2","G#2","B2"]},
      {notes:["A3"],      accomp:["A2","E3","A3"]},

      // ===== A Section 3 — Final =====
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2","E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","E3","A3"]},
      {notes:["C4"],  accomp:[]},
      {notes:["E4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3"]},
      {notes:["B4"],  accomp:["E2","G#2","E3"]},
      {notes:["E4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2","C3","E3","A3"]},  // final chord
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  //  Rondo alla Turca — W.A. Mozart   (上級: 慣れてきたら)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "turkish_march",
    title: "トルコ行進曲",
    composer: "W.A. モーツァルト",
    level: 2,
    bpm: 60,
    events: [
      // ===== A Section — Rondo theme (A minor) =====
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["D5"],  accomp:["A2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["E5"],  accomp:["E3","A3"]},
      {notes:["F5"],  accomp:["A2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:["E2","G#2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["E2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["G#2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:["E3"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:[]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G4"],  accomp:[]},
      {notes:["F#4"], accomp:["D3"]},
      {notes:["E4"],  accomp:["E2","G#2","B2"]},

      // ===== Episode — running scales =====
      {notes:["E5"],  accomp:["C3","E3","G3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["A5"],  accomp:["C3","G3"]},
      {notes:["G5"],  accomp:["G2"]},
      {notes:["F5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["E5"],  accomp:["C3","E3","G3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["G5"],  accomp:[]},
      {notes:["A5"],  accomp:["C3","G3"]},
      {notes:["G5"],  accomp:["G2","B2","D3"]},
      {notes:["F5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:["C3","E3","G3"]},
      {notes:["D5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["E5"],  accomp:[]},
      {notes:["F5"],  accomp:["C3","G3"]},
      {notes:["E5"],  accomp:["G2","B2"]},
      {notes:["D5"],  accomp:[]},

      // ===== A Section return + cadence =====
      {notes:["C5"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["E2","G#2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["C5"],  accomp:["A2"]},
      {notes:["D5"],  accomp:[]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["E5"],  accomp:[]},
      {notes:["F5"],  accomp:["A2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["D#5"], accomp:["E2","G#2"]},
      {notes:["E5"],  accomp:[]},
      {notes:["B4"],  accomp:["A2"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["B4"],  accomp:["E3","A3"]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["C5"],  accomp:["A2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["B4"],  accomp:[]},
      {notes:["C5"],  accomp:["E3","A3"]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4"],  accomp:[]},
      {notes:["G#4"], accomp:["E2","G#2","B2"]},
      {notes:["A4"],  accomp:["A2"]},
      {notes:["E5"],  accomp:["A2"]},
      {notes:["F5"],  accomp:[]},
      {notes:["D5"],  accomp:["E2","B2"]},
      {notes:["C5"],  accomp:[]},
      {notes:["B4"],  accomp:[]},
      {notes:["A4","C5","E5"], accomp:["A2","E3","A3"]},
    ],
  },
];
